services:
  postgres:
    image: postgres:18
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - pgdata:/var/lib/postgresql

  pocket-postgres:
    image: postgres:18
    container_name: pocket-postgres
    restart: always
    environment:
      POSTGRES_USER: pocket-id
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pocket-id
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - pgdata-pocket-id:/var/lib/postgresql

  pocket-id:
    image: ghcr.io/pocket-id/pocket-id:latest
    ports:
      - "${POCKET_ID_PORT:-1411}:1411"
    environment:
      APP_URL: ${POCKET_ID_APP_URL:-http://localhost:1411}
      DB_PROVIDER: postgres
      DB_CONNECTION_STRING: postgresql://${POSTGRES_USER:-pocket-id}:${POSTGRES_PASSWORD:-password}@pocket-postgres:5432/${POSTGRES_DB:-pocket-id}
      ENCRYPTION_KEY: ${POCKET_ID_ENCRYPTION_KEY:-dev-only-change-me-in-production!}
      TRUST_PROXY: "false"
    volumes:
      - pocketid_data:/app/data
    depends_on:
      pocket-postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  pgdata:
  pgdata-pocket-id:
  pocketid_db:
  pocketid_data:
