apiVersion: v2
name: go-server
description: A Helm chart for the Go server template application
type: application
version: 0.0.0-2
appVersion: "0.0.0-2"
keywords:
  - go
maintainers:
  - name: Tom Ludwig
    email: tomludwig@duck.com
