apiVersion: v2
name: go-server
description: A Helm chart for the Go server template application
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - go
maintainers:
  - name: Tom Ludwig
    email: tomludwig@duck.com

